### ISSUE TITLE
I try to execute Static Analyzer which using Android Studio build it but having problem

### ISSUE THREAD

**Issue by william31212** [kekeLian/StrawFuzzer#1]
In the Usage 4. Generate static analysis result with our static analyzer.

I try to Using the Android Studio to run the static analyzer, but the Soot's class & method still cannot find in the source. Is any jdk or other need to import ?

The result is down below. 
![](https://user-images.githubusercontent.com/40447900/160901565-2a0b2906-7e87-4434-ba48-55136ad45264.png)

**Comment by yatooimh** [comment]
Maybe you can import a jar through File->Project Structure->Dependencies
I solved this problem through importing the following file. As I cannot upload jar here, you can import it after changing the file extension from zip to jar:
[sootclasses-trunk-jar-with-dependencies.zip](https://github.com/kekeLian/StrawFuzzer/files/8629796/sootclasses-trunk-jar-with-dependencies.zip)

**Comment by LianKee** [comment]
The static analysis module is a Java program rather than an Android program, you should run it with other IDEs, such as IDEA.

**Comment by LianKee** [comment]
As for the unfound Soot Classes, you should import soot jar, which can be downloaded from Soot's official website. Or you can refer to @yatooimh's comments.
