### ISSUE TITLE
How to get ServicesList in target system?

### ISSUE THREAD

**Issue by X1aoR0** [kekeLian/StrawFuzzer#2]
I have read the StaticAnalyzer and I noticed that it need a _AllServices.txt. The project don't supply that.
Can someone tell me how to get a _AllServices.txt? please.

**Comment by LianKee** [comment]
You can first get system service list with their IInterface class information via "adb shell service list"

` ✘   adb shell service list

Found 235 services:
0	DockObserver: []
1	SurfaceFlinger: [android.ui.ISurfaceComposer]
2	accessibility: [android.view.accessibility.IAccessibilityManager]
3	account: [android.accounts.IAccountManager]
4	activity: [android.app.IActivityManager]
......`

Then you can scan these classes to get the declared public service interfaces

**Comment by X1aoR0** [comment]
> You can first get system service list with their IInterface class information via "adb shell service list"
> 
> ` ✘ adb shell service list
> 
> Found 235 services: 0 DockObserver: [] 1 SurfaceFlinger: [android.ui.ISurfaceComposer] 2 accessibility: [android.view.accessibility.IAccessibilityManager] 3 account: [android.accounts.IAccountManager] 4 activity: [android.app.IActivityManager] ......`
> 
> Then you can scan these classes to get the declared public service interfaces

Great! I have read papers to identify services with some static analysis methods.  I really never think it could be done in such a simple way, hah.

**Comment by SeonAh-Yoo** [comment]
I tried to get _AllServices.txt through "adb shell service list". I got service name and stub class name through it but I couldn't get extra information needed for running StaticAnalyzer. I hope you to give me some instructions about how to make _AllServices.txt fitting to formats written in source code. Thank you.
